apiVersion: v1
kind: PersistentVolume
metadata:
  name: blog-nfspv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/usb/500/web/blog/posts
    server: ubumac
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-nfspvc
  namespace: webapps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: blog-nfspv
---
apiVersion: v1
kind: Secret
metadata:
  namespace: webapps
  name: minio-credentials
type: Opaque
stringData:
  accessKey: lucarv
  secretKey: lucaPWD$MinI0
  endpoint: minio-service.minio.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  namespace: webapps
  name: blogt
spec:
  selector:
    app: blogt
  ports:
    - protocol: TCP
      port: 3000
      name: http
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: webapps
  name: blogt
  labels:
    app: blogt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogt
  template:
    metadata:
      labels:
        app: blogt
    spec:
      containers:
      - name: blogt
        image: lucarv/blogt-too:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
            name: blogt
        env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: accessKey
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: secretKey
          - name: MINIO_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: endpoint
        volumeMounts:
          - name: blogposts
            mountPath: /app/posts
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
      volumes:
        - name: blogposts
          persistentVolumeClaim:
            claimName: blog-nfspvc
