apiVersion: v1
kind: PersistentVolume
metadata:
  name: blog-nfspv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/usb/500/web/blog/posts
    server: ubumac
  persistentVolumeReclaimPolicy: Retain  # Ensures the volume is retained even after the PVC is deleted
  mountOptions:
    - nolock   # Improve security and performance by disabling file locking, if suitable for your use case

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-nfspvc
  namespace: webapps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: blog-nfspv

---
apiVersion: v1
kind: Secret
metadata:
  namespace: webapps
  name: minio-credentials
type: Opaque
stringData:
  accessKey: lucarv
  secretKey: lucaPWD$MinI0
  endpoint: minio-service.minio.svc.cluster.local
# Use Kubernetes secrets instead of hardcoding sensitive values directly in the environment variables or YAML files

---
apiVersion: v1
kind: Service
metadata:
  namespace: webapps
  name: blogt
spec:
  selector:
    app: blogt
  ports:
    - protocol: TCP
      port: 3000
      name: http
  type: LoadBalancer
  externalTrafficPolicy: Local  # Ensure that the source IP is preserved when using LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: webapps
  name: blogt
  labels:
    app: blogt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogt
  template:
    metadata:
      labels:
        app: blogt
    spec:
      securityContext:
        runAsUser: 1000  # Run as non-root user for improved security
        runAsGroup: 1000
        fsGroup: 1000  # Ensures the pod has the necessary file system access
        allowPrivilegeEscalation: false  # Prevents privilege escalation for security
      containers:
        - name: blogt
          image: lucarv/blogt:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"   # Reduced memory request to 256 MB (based on observed usage)
              cpu: "100m"       # Reduced CPU request to 100 milli-CPU (0.1 CPU)
            limits:
              memory: "512Mi"   # Set memory limit to 512 MB
              cpu: "500m"       # Set CPU limit to 500 milli-CPU (0.5 CPU)
          ports:
            - containerPort: 80
              name: blogt
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: accessKey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: secretKey
            - name: MINIO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: endpoint
          volumeMounts:
            - name: blogposts
              mountPath: /app/posts
      volumes:
        - name: blogposts
          persistentVolumeClaim:
            claimName: blog-nfspvc
      terminationGracePeriodSeconds: 30  # Graceful shutdown for pods
      livenessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 60
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /readiness
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 30
        failureThreshold: 3
